export const navItems = [
  { id: "overview", label: "1. 系统概述" },
  { id: "arch", label: "2. 总体架构" },
  { id: "features", label: "3. 系统总体功能" },
  { id: "r-collect", label: "4. 接触电阻采集" },
  { id: "i-collect", label: "5. 电流采集" },
  { id: "plc", label: "6. PLC通信与控制" },
  { id: "loop", label: "7. 试验流程控制" },
  { id: "speed", label: "8. 动作速度测算" },
  { id: "protect", label: "9. 保护停机机制" },
  { id: "chart", label: "10. 实时曲线监测" },
  { id: "save", label: "11. 数据存储与回放" },
  { id: "db", label: "12. 数据库设计" },
  { id: "protocol", label: "13. 通信协议设计" },
  { id: "classes", label: "14. 软件结构" },
  { id: "conclusion", label: "15. 关键技术与总结" },
  { id: "four-to-one", label: "16. 4拖1方案拓展" },
  { id: "hard-qa", label: "17. 重难点问题与代码解答" },
  { id: "algo", label: "18. 模块框图与关键算法" },
] as const;
